(wip)Project resource endpoint
AgileVentures/WebsiteOneBackendApi pull request #36
Opened 2019-10-28 15:01 UTC by cesswairimu

#### Fixes issue #35 

- Project model creation
- Project controller endpoints
- Tests

- [ ] Tests all green tests and all builds passes :green_heart:
- [ ] PR well-named, issue linked :paperclip: and no merge conflicts.
- [ ] Request review from other contributors

##### Screenshots(if appropriate)

2019-11-05 06:58 UTC, aonomike commented on db/schema.rb
> +# This file is the source Rails uses to define your schema when running `rails
Hi @cesswairimu thanks for working on this, as mentioned in the README contributing PR, we were meant to re-use the schema.rb file for the current WSO project. So maybe its not a good idea to delete stuff from this file completely? What do you think?

2019-11-05 07:03 UTC, aonomike commented on db/schema.rb
> +# This file is the source Rails uses to define your schema when running `rails
I updated this PR with dev and it now seems to be failing tests due to the deletions on this files...

2019-11-05 07:05 UTC, aonomike commented
Hi @cesswairimu thanks for working on this one, maybe just needs us adding tests and then we are good to go? We can plan to pair on the tests incase we are both available at the same time :D

2019-11-05 08:00 UTC, cesswairimu commented
Hi @aonomike, I already started on the tests will push them in the course of the week...Will try rebasing and see if the build will pass. Thanks

2019-11-05 19:50 UTC, aonomike commented
Wow great @cesswairimu thanks!

2019-11-07 14:51 UTC, cesswairimu commented
@aonomike this is ready thanks

2019-11-10 20:16 UTC, cesswairimu commented
Hey @aonomike, I still don't see any new comments...Thanks

2019-11-28 15:43 UTC, gr1d99 requested changes
hey @cesswairimu great job, I have added some more review comments, kindly have a look at them

2019-11-28 15:43 UTC, gr1d99 commented on app/controllers/projects_controller.rb
> +  before_action :find_project, only: [:update, :destroyi, :show]
`destroyi` :joy:

2019-11-28 15:43 UTC, gr1d99 commented on app/controllers/projects_controller.rb
> +      render status: 404
I believe we have a rescue that handles `404` errors, please do check this [link](https://github.com/AgileVentures/WebsiteOneBackendApi/blob/11656b5d3b8ca31ccc54d074b316a16ba619fa00/app/controllers/application_controller.rb#L2)

2019-11-28 15:43 UTC, gr1d99 commented on app/models/project.rb
> +validates_presence_of :title, :description, :status
it is always preferred to write single attribute validation over multiple attributes validation in a single line, please refer [here](https://github.com/rubocop-hq/rails-style-guide#single-attribute-validations)

2019-11-28 15:43 UTC, gr1d99 commented on config/database.yml
> +  password: 'admin63'
this exposes some sensitive info, it would be better to leave it blank instead

2019-11-28 15:43 UTC, gr1d99 commented on app/controllers/projects_controller.rb
> +class ProjectsController < ApplicationController
this may not be necessary but we can use **symbols** for response status code in the entire controller just for consistency

2019-11-28 17:41 UTC, cesswairimu commented
done..with the changes...thanks all

2019-12-10 16:19 UTC, aonomike commented
Hi @cesswairimu Thanks again for this one, I am working on some tests for this PR to bump the  test coverage :)

2019-12-10 18:44 UTC, cesswairimu commented
Thanks MIke!, let me know where I can help

2020-03-24 14:58 UTC, NickSchimek commented
@cesswairimu I rebased the branch to pull in the develop branch. 
A request spec has also been created.

2020-03-24 15:25 UTC, cesswairimu commented
Thanks @NickSchimek

2020-05-20 18:18 UTC, aonomike approved these changes
Looks good to me. Thanks @cesswairimu and team

2020-05-20 18:18 UTC, aonomike commented on config/database.yml
> +  username: lenovo
Hi @cesswairimu maybe we need to use a `.env` file 🤔 ?

2020-05-20 18:18 UTC, aonomike commented on app/controllers/projects_controller.rb
> +      render status: 404
hi @cesswairimu we may not need the else since we have [this set up in the application controller](https://github.com/AgileVentures/WebsiteOneBackendApi/blob/d9eea6bce4381a1be385721e699346c9ffd626e8/app/controllers/application_controller.rb#L2)?

2020-05-20 18:27 UTC, gr1d99 approved these changes

2020-05-20 18:36 UTC, merged

2020-05-21 07:02 UTC, cesswairimu commented
Thanks all who helped on this :tada: